apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-aws-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8s-aws-operator
  #annotations:
  #  eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/k8s-aws-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-aws-operator
  labels:
    app.kubernetes.io/name: k8s-aws-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["aws.k8s.logmein.com"]
  resources: ["eips", "enis"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-aws-operator
  labels:
    app.kubernetes.io/name: k8s-aws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-aws-operator
subjects:
- kind: ServiceAccount
  name: k8s-aws-operator
  namespace: kube-system

# for leader election:
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: k8s-aws-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8s-aws-operator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["k8s-aws-operator"]
  verbs: ["delete","get","update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: k8s-aws-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8s-aws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-aws-operator
subjects:
  - kind: ServiceAccount
    name: k8s-aws-operator
    namespace: kube-system
